import "./ultralight-italic/font.css";
import "./light-italic/font.css";
import "./thin-italic/font.css";
import "./regular/font.css";
import "./medium/font.css";
import "./semibold-italic/font.css";
import "./bold/font.css";
import "./heavy-italic/font.css";
import "./black-italic/font.css";
